version: '2.3'

services:
  tf-gpu:
    image: tensorflow/tensorflow:1.11.0-gpu-py3
    runtime: nvidia
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: bash
  tf:
    image: tensorflow/tensorflow:1.11.0-py3
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: bash
  tf-train:
    image: tensorflow/tensorflow:1.11.0-py3
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: ./train.sh
