version: '2.3'

services:
  gpu:
    image: tensorflow/tensorflow:1.11.0-gpu-py3
    runtime: nvidia
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: bash
  gpu-train:
    image: tensorflow/tensorflow:1.11.0-gpu-py3
    runtime: nvidia
    volumes:
      - .:/home/project
    working_dir: /home/project
    command: ./train.sh
  gpu-interact:
    image: tensorflow/tensorflow:1.11.0-gpu-py3
    runtime: nvidia
    volumes:
      - .:/home/project
    working_dir: /home/project
    command: ./interact.sh

  cpu:
    image: tensorflow/tensorflow:1.11.0-py3
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: bash
  cpu-train:
    image: tensorflow/tensorflow:1.11.0-py3
    volumes:
    - .:/home/project
    working_dir: /home/project
    command: ./train.sh
  cpu-interact:
    image: tensorflow/tensorflow:1.11.0-py3
    volumes:
      - .:/home/project
    working_dir: /home/project
    command: ./interact.sh
